# Generated by Django 4.2.6 on 2023-10-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customuser_otp_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
