# Generated by Django 4.2.6 on 2023-10-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customuser_reset_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset',
            field=models.BooleanField(default=False),
        ),
    ]
