# Generated by Django 4.2.6 on 2023-10-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_customuser_new_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_entry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
