# Generated by Django 4.2.6 on 2023-10-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_customuser_otp_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='otp_entry',
            new_name='otp_expiry',
        ),
    ]
